### ISSUE TITLE
deepai doesn't work

### ISSUE THREAD

**Issue by wioniqle-q** [Siris2314/NecroAtomicBot#214]
deepai doesn't work

**Comment by Siris2314** [comment]
What do you mean it doesn't work could you be more specific please?

**Comment by wioniqle-q** [comment]
> What do you mean it doesn't work could you be more specific please?

https://github.com/deepai-org/deepai-js-client/issues/23

go to here

**Comment by Siris2314** [comment]
You sure it's not cause you don't have a valid key?

**Comment by Siris2314** [comment]
> > What do you mean it doesn't work could you be more specific please?
> 
> [deepai-org/deepai-js-client#23](https://github.com/deepai-org/deepai-js-client/issues/23)
> 
> go to here

check API key and show me how you imported deep api

**Comment by wioniqle-q** [comment]
```js
const deepai = require('deepai')
const nsfwtoken = "c9137212-f94c-43c5-9f2c-5d23ceebb310"
deepai.setApiKey(nsfwtoken);

 if(message.attachments.first()){
    await nsfwschema.findOne({Server:message.guild.id}, async(err,data)=>{
        if(!data || !data.Server == null) return;

        const image = message.attachments.first().url

        let response = await deepai.callStandardApi("nsfw-detector", {
            image:image,
        })
        const score = response.output.nsfw_score
        
        if(score + .2 >= .5){
            message.delete()
            message.channel.send('NO NSFW Images allowed')
        }








    })
  }

**Comment by Siris2314** [comment]
> ```js
> const deepai = require('deepai')
> const nsfwtoken = "c9137212-f94c-43c5-9f2c-5d23ceebb310"
> deepai.setApiKey(nsfwtoken);
> 
>  if(message.attachments.first()){
>     await nsfwschema.findOne({Server:message.guild.id}, async(err,data)=>{
>         if(!data || !data.Server == null) return;
> 
>         const image = message.attachments.first().url
> 
>         let response = await deepai.callStandardApi("nsfw-detector", {
>             image:image,
>         })
>         const score = response.output.nsfw_score
>         
>         if(score + .2 >= .5){
>             message.delete()
>             message.channel.send('NO NSFW Images allowed')
>         }
> 
> 
> 
> 
> 
> 
> 
> 
>     })
>   }
> ```

I will do some testing on my side and see if I get the same issue

**Comment by Siris2314** [comment]
> ```js
> ```js
> const deepai = require('deepai')
> const nsfwtoken = "c9137212-f94c-43c5-9f2c-5d23ceebb310"
> deepai.setApiKey(nsfwtoken);
> 
>  if(message.attachments.first()){
>     await nsfwschema.findOne({Server:message.guild.id}, async(err,data)=>{
>         if(!data || !data.Server == null) return;
> 
>         const image = message.attachments.first().url
> 
>         let response = await deepai.callStandardApi("nsfw-detector", {
>             image:image,
>         })
>         const score = response.output.nsfw_score
>         
>         if(score + .2 >= .5){
>             message.delete()
>             message.channel.send('NO NSFW Images allowed')
>         }
> 
> 
> 
> 
> 
> 
> 
> 
>     })
>   }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> I will do some testing on my side and see if I get the same issue
> ```

Yeah idk what your issue is cause mine is working completely fine, maybe generate a new token and see

**Comment by wioniqle-q** [comment]
I just created a new account, and I get the same mistake, and you can give me your code?

**Comment by Siris2314** [comment]
> I just created a new account, and I get the same mistake, and you can give me your code?

The code is on my GitHub, as long as you copied it correctly and are using your API key it should work, did you install deepai and correctly import it?

**Comment by wioniqle-q** [comment]
yes, I did everything right, but it doesn't work.

**Comment by Siris2314** [comment]
> yes, I did everything right, but it doesn't work.
Idk what to say if you copied the code exactly how it is up you should not be having any issues,
https://deepai.org/machine-learning-model/nsfw-detector,
make sure you follow the exact same steps

**Comment by Siris2314** [comment]
Also you have a 401 error, an authorization error meaning that your API key is not valid
