### ISSUE TITLE
Early Warning to Alexa-Bot-API-V3

### ISSUE THREAD

**Issue by KazutoKashima** [Siris2314/NecroAtomicBot#229]
Hey there, as a Cease and Desist to the Alexa-Bot-API-v3 request has been put through and approved,
I'm giving 8 days to all users before the project gets put down.

I advice finding something similar while the project is being taken down

See here: [Cease and Desist](https://github.com/KazutoKashima/alexa-bot-api-v3/issues/1)

Thanks.

**Comment by Siris2314** [comment]
Aight thanks, will do
