### ISSUE TITLE
Days as Number

### ISSUE THREAD

**Issue by NotSoMik** [Siris2314/NecroAtomicBot#297]
Hello (about the anti alt system) I saw you put Days: String [here](https://github.com/Siris2314/NecroAtomicBot/blob/main/schemas/anti-alt.js#L10) but it wouldnt be better to use Days: Number? Since you also used interaction.options.getNumber in your command

**Comment by Siris2314** [comment]
Sure that works, In mongo i like storing it more as a String but up to you
