### ISSUE TITLE
HacktoberFest 2022 -  Conversion to DJv14

### ISSUE THREAD

**Issue by Siris2314** [Siris2314/NecroAtomicBot#304]
One major issue currently is converting the slash commands to version v14 of Discord.JS, so as a Hacktoberfest Challenge, you can contribute by converting the slash commands to the latest version

**Comment by NotSoMik** [comment]
I suggest you to remake the whole project since its kinda a mess you should clean everything up. Your main files has over 2k lines and it's not that good yk. This is just a tip
