### ISSUE TITLE
Chat-GPT System added

### ISSUE THREAD

**Issue by Siris2314** [Siris2314/NecroAtomicBot#306]
The chatbot system now uses the Chat-GPT Api from OpenAI, currently I am trying to figure out a way to optimize requests with costs

**Comment by Hypwreck** [comment]
So now For the GPT to work, we will be needing an API, and that API is not for free, so for Chat GPT to work the user gotta buy the API from OpenAI.

**Comment by Siris2314** [comment]
Closed, will be using HF instead to ensure open source
